### ISSUE TITLE
AssertionError: Strides 16 16 are not log2 contiguous

### ISSUE THREAD

**Issue by dzlhk** [lizhaoliu-Lec/CCSE#2]
AssertionError: Strides 16 16 are not log2 contiguous
错误
<img width="846" alt="image" src="https://user-images.githubusercontent.com/14235113/200155073-a2865ef8-8379-4dbc-8e5a-4c4def777bfe.png">

**Comment by lizhaoliu-Lec** [comment]
Using this config (config/instance_segmentation/mask_rcnn_R_50_FPN_3x_handwritten.yaml) will resolve this issue.
