### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by zi1zi** [lizhaoliu-Lec/CCSE#3]
![image](https://user-images.githubusercontent.com/48040139/200223256-8479b6ee-8ebb-4b20-95c8-fe003a74723a.png)
![image](https://user-images.githubusercontent.com/48040139/200223513-42202cd0-e123-4ed5-a779-e26d8c92b6d5.png)

您好，我明明有这个文件夹，为啥说我没有呀

**Comment by lizhaoliu-Lec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        根路径不对哈（见橙色矩形框）
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月7日 11:56
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [lizhaoliu-Lec/CCSE] 数据集问题 (Issue #3)
        
      
    
  
  





您好，我明明有这个文件夹，为啥说我没有呀
