### ISSUE TITLE
路径

### ISSUE THREAD

**Issue by zi1zi** [lizhaoliu-Lec/CCSE#4]
您好，您刚才回复我的邮件我在我这看是乱的
![image](https://user-images.githubusercontent.com/48040139/200238830-bf0d77ac-973f-4524-9a9b-49d746088bd2.png)

**Comment by lizhaoliu-Lec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    这次放到附件了
    
    
     
    
        
                    
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月7日 14:17
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [lizhaoliu-Lec/CCSE] 路径 (Issue #4)
        
      
    
  
  

您好，您刚才回复我的邮件我在我这看是乱的

**Comment by lizhaoliu-Lec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    图片见附件
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月7日 14:17
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [lizhaoliu-Lec/CCSE] 路径 (Issue #4)
        
      
    
  
  

您好，您刚才回复我的邮件我在我这看是乱的

**Comment by lizhaoliu-Lec** [comment]
![snipeshot_20221107142220](https://user-images.githubusercontent.com/38394970/200239891-58f0013f-3903-4b36-a16f-cbd0c16eda74.jpg)

**Comment by lizhaoliu-Lec** [comment]
可通过配置文件中的``DATA_ROOT``字段修改数据集存放路径

**Comment by zi1zi** [comment]
![image](https://user-images.githubusercontent.com/48040139/200242658-58ce6560-466b-402e-a2bf-6d9f9e12c045.png)
谢谢您的及时回复哈，您直接在这里回复是最好的，通过邮件的回复我始终感觉样式比较乱，但是现在又出现了这个问题

**Comment by lizhaoliu-Lec** [comment]
依然是路径问题，img是NoneType说明图片没读取出来

**Comment by zi1zi** [comment]
您好，又出现新的错误了
![image](https://user-images.githubusercontent.com/48040139/200246735-73aef6c6-9fc7-4c3b-ae70-b65f023e97b6.png)

**Comment by lizhaoliu-Lec** [comment]
使用这个配置文件：config/instance_segmentation/mask_rcnn_R_50_FPN_3x_handwritten.yaml

**Comment by zi1zi** [comment]
![image](https://user-images.githubusercontent.com/48040139/200268992-4f11938e-54c6-49fe-9c8d-bbf5c5f77b01.png)
您好，训练没有多长时间就停掉了

**Comment by lizhaoliu-Lec** [comment]
这应该是你的服务器资源问题。代码中没有“已杀死”的报错提示。我在12GB的Titan XP上可以正常训练

**Comment by zi1zi** [comment]
![image](https://user-images.githubusercontent.com/48040139/200294121-bbc83415-96ed-4eba-9418-0da5ee12fc39.png)
您好，通过后台挂起的方式跑代码会出现这个错误

**Comment by lizhaoliu-Lec** [comment]
采用tmux即可

**Comment by zi1zi** [comment]
您好，我11G显存报RuntimeError: CUDA out of memory，是降低这个参数吗
![image](https://user-images.githubusercontent.com/48040139/200459099-1fd1b603-9eff-4365-8570-40c2297fe255.png)
本项目中的STEPS参数具体指的啥，没有epoch吗，

**Comment by lizhaoliu-Lec** [comment]
是的
