### ISSUE TITLE
ModuleNotFoundError: No module named 'detectron2'

### ISSUE THREAD

**Issue by zi1zi** [lizhaoliu-Lec/CCSE#5]
不好意思哈，我先自己解决一下啊

**Comment by zi1zi** [comment]
您好，使用tmux跑模型时就出出现一系列问题，哪个包没有安装等
![image](https://user-images.githubusercontent.com/48040139/200981833-0e972119-937a-4d1e-853c-3b2fa64b38b7.png)
但不使用tmux就可以正常运行

**Comment by lizhaoliu-Lec** [comment]
没遇到过相关问题

**Comment by zi1zi** [comment]
您用的cuda版本，python版本，pytorch版本是多少呢哈，我这好多奇怪的问题

**Comment by lizhaoliu-Lec** [comment]
Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04)
pytorch                   1.7.1           py3.6_cuda11.0.221_cudnn8.0.5_0    pytorch
cudatoolkit               11.0.221             h6bb024c_0    defaults
detectron2                0.4+cu110                pypi_0    pypi

**Comment by zi1zi** [comment]
我使用这个mask_rcnn_R_50_FPN_3x_handwritten_test.yaml进行测试，生成的文件夹都是空的，您确定mask_rcnn_R_50_FPN_3x_handwritten_test.yaml中的参数是对的吗

**Comment by lizhaoliu-Lec** [comment]
请问配置文件中的 ``OUTPUT_DIR`` 和 ``OUTPUT_ID`` 是否配置正确？

**Comment by zi1zi** [comment]
没有问题，是正确的

**Comment by zi1zi** [comment]
![image](https://user-images.githubusercontent.com/48040139/201604102-b3d0edaa-de8e-4564-933a-5ead0d582788.png)
您这一块不应该test.json吗

**Comment by lizhaoliu-Lec** [comment]
> 没有问题，是正确的

那需要提供更多的信息我才能诊断

**Comment by lizhaoliu-Lec** [comment]
> ![image](https://user-images.githubusercontent.com/48040139/201604102-b3d0edaa-de8e-4564-933a-5ead0d582788.png) 您这一块不应该test.json吗

val/test都可以

**Comment by zi1zi** [comment]
![image](https://user-images.githubusercontent.com/48040139/201605787-30a1da8d-7022-4d11-b788-6d72fbc7ee89.png)
麻烦您看一下哪有问题哈

**Comment by lizhaoliu-Lec** [comment]
请问能否提供命令行的输出结果，文件保存的路径信息代码中打印出来了
![image](https://user-images.githubusercontent.com/38394970/201606396-15402022-b433-43fc-9dfd-8bcda161540d.png)

**Comment by zi1zi** [comment]
好像在控制台中没有输出您红框中的两行字

**Comment by lizhaoliu-Lec** [comment]
请问使用的测试命令是什么？

**Comment by zi1zi** [comment]
PYTHONPATH=$PYTHONPATH:./ python -u scripts/inference_instance.py --config config/instance_segmentation/mask_rcnn_R_50_FPN_3x_handwritten_test.yaml

**Comment by lizhaoliu-Lec** [comment]
将该字段取消注释即可
![image](https://user-images.githubusercontent.com/38394970/201615129-699c0222-fb64-4d11-920b-2c371cc46b65.png)
