### ISSUE TITLE
运行test时产生的疑问

### ISSUE THREAD

**Issue by NiteCat-zr** [lizhaoliu-Lec/CCSE#6]
为何测试test时也要json标签，那如果我去测试新的图片应该怎么做。感谢回复

**Comment by lizhaoliu-Lec** [comment]
为了评估模型在验证/测试集上的性能，所以需要提供对应的json标签。
实际上需要用到json标签的只有这一行代码（initializer里面也用到了）
![image](https://user-images.githubusercontent.com/38394970/202139104-b2b7467a-5988-45e8-9078-4e5557932717.png)

按照readme的建议，实现你自己的initializer，同时不要调用evaluate函数即可
![image](https://user-images.githubusercontent.com/38394970/202139608-a5cf1969-3e11-4c35-9e7d-0698505c5fdf.png)

**Comment by NiteCat-zr** [comment]
感谢您的回复，我去尝试一下，如果有问题再向您请教
