### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by zi1zi** [lizhaoliu-Lec/CCSE#7]
您好，您实例分割的数据集是公开的数据集吗，最近想研究一下用深度学习提取字体骨架，但是没有找到公开的数据集，您是否有字体数据集的相关网站呢

**Comment by lizhaoliu-Lec** [comment]
1. 我们的实力分割数据集是自己收集+标注的数据集
2. 目前没有字体骨架相关的资源可以分享，之前没有往这个方向做
3. 提供一个可行的思路：可以利用我们逐笔画的标注，提取出一个个笔画，然后对这些笔画采用细化算法，再加一些人工的后处理，估计就能得到一个大概的结果了

**Comment by zi1zi** [comment]
谢谢您的及时回复，我的一个想法就是用深度学习去提取字体骨架相较于传统的算法有所改进，但是您提供的方案是用传统细化算法去提取字体骨架，如果数据集都是用传统算法去制作的话，深度学习模型就算是再好最多也就是不断的去逼近真图（由传统的算法制作的），那深度学习不可能优于传统算法，不知道我这样理解对不对

**Comment by lizhaoliu-Lec** [comment]
我的意思先使用细化算法得到一个大概的结果，再后期人工去调整。
这样总比纯人工标注要快得多
