### ISSUE TITLE
请教一下有关可视化的问题

### ISSUE THREAD

**Issue by ZzBobo0915** [lizhaoliu-Lec/CCSE#8]
训练图片和测试图片的像素大部分都在100px*100px以下，但是可视化结果出来的图片大小为固定的1920*1440，是先将图片固定到1920*1440再代入模型中测试，还是说先测试再对图片进行放大处理，或者是别的方法，不太懂这个是怎么做的。

**Comment by lizhaoliu-Lec** [comment]
- 模型的训练采用的像素大小是 [112, 120] pixel x [112, 120] pixel (四种排列组合)

- 模型的测试采用的像素大小是 112 pixel x 112 pixel

- 可视化采用的是 scripts/inference_instance.py/OurVisualizer 类（继承derectron2的Visualizer），其会对图片进行放大处理，放大的倍数由 scale 参数设置

**Comment by ZzBobo0915** [comment]
我尝试修改了scale的值，但是并没有影响到可视化结果，不知道是什么原因

**Comment by lizhaoliu-Lec** [comment]
按理来说应该可以改变图像尺寸才对。可以试试输出一下源码的相关信息进行 debug
detectron2\utils\visualizer.py, line 360, print("==> self.img.shape: {}".format(self.img.shape))

**Comment by ZzBobo0915** [comment]
好的 我去尝试一下，感谢！
